### ISSUE TITLE
Limit the maximum and minimum zoom level

### ISSUE THREAD

**Issue by hanchao** [maplibre/maplibre-rs#161]
Keep zooming in or zooming out,  program will crashe. 

## 🤔 Expected Behavior

Need to limit maximum and minimum zoom level

## 😯 Current Behavior

Keep zooming in until the program crashe

'''
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 30.42
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 30.52
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 30.71
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 30.96
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 31.21
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 31.36
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 31.53
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 31.85
[2022-07-18T12:36:49Z INFO  maplibre::context] zoom: 32.16
thread 'main' panicked at 'attempt to add with overflow', maplibre/src/coords.rs:584:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-07-18T12:36:49Z INFO  wgpu_core::hub] Dropping Global
[2022-07-18T12:36:49Z INFO  wgpu_core::device] Destroying 12 command encoders
'''

Keep zooming out until the program crashe

'''
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -30.15
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -30.41
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -30.66
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -30.9
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -31.13
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -31.35
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -31.56
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -31.76
[2022-07-18T12:35:05Z INFO  maplibre::context] zoom: -31.95
thread 'main' panicked at 'attempt to add with overflow', maplibre/src/coords.rs:584:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-07-18T12:35:05Z INFO  wgpu_core::hub] Dropping Global
[2022-07-18T12:35:05Z INFO  wgpu_core::device] Destroying 5 command encoders
'''

## 🌍 Your Environment

* Desktop
    - Operating System: macOS 12.2.1

**Comment by DerKarlos** [comment]
Oops, I started with this and commented in the wrong Issue #73

**Comment by maxammann** [comment]
Alright no worries!

**Comment by maxammann** [comment]
We should also directly address the overflows. E.g. returning errors/options when we would hit the overflows.
